begin;

create type public.venue_status as enum (
  'draft',
  'pending_approval',
  'approved',
  'rejected',
  'changes_requested'
);

create type public.venue_photo_kind as enum ('logo', 'cover', 'gallery');

create table public.venues (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null unique references public.profiles (id) on delete restrict,
  commercial_name text not null,
  slug text not null unique,
  description text not null,
  phone_e164 text not null,
  whatsapp_e164 text not null,
  address text not null,
  zone text not null,
  city text not null default 'Santa Cruz de la Sierra',
  latitude numeric(9, 6) not null,
  longitude numeric(9, 6) not null,
  status public.venue_status not null default 'draft',
  review_note text,
  submitted_at timestamptz,
  reviewed_at timestamptz,
  reviewed_by uuid references public.profiles (id) on delete set null,
  approved_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint venues_name_length check (char_length(commercial_name) between 3 and 120),
  constraint venues_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint venues_description_length check (char_length(description) between 30 and 2000),
  constraint venues_phone_format check (phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  constraint venues_whatsapp_format check (whatsapp_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  constraint venues_address_length check (char_length(address) between 5 and 240),
  constraint venues_zone_length check (char_length(zone) between 2 and 100),
  constraint venues_city_length check (char_length(city) between 2 and 100),
  constraint venues_latitude_range check (latitude between -90 and 90),
  constraint venues_longitude_range check (longitude between -180 and 180),
  constraint venues_review_note_length check (review_note is null or char_length(review_note) between 5 and 1000)
);

comment on table public.venues is 'Complejos deportivos. En el MVP cada propietario administra un solo complejo.';
comment on column public.venues.status is 'Solo approved puede mostrarse públicamente.';
comment on column public.venues.latitude is 'Coordenada independiente del proveedor de mapas que se elija más adelante.';

create index venues_status_idx on public.venues (status);
create index venues_city_zone_idx on public.venues (city, zone);

create trigger venues_set_updated_at
before update on public.venues
for each row execute function private.set_updated_at();

create table public.services (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  icon text not null,
  sort_order smallint not null default 0,
  is_active boolean not null default true,
  constraint services_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint services_name_length check (char_length(name) between 2 and 80)
);

insert into public.services (slug, name, icon, sort_order) values
  ('estacionamiento', 'Estacionamiento', 'car', 10),
  ('banos', 'Baños', 'restroom', 20),
  ('duchas', 'Duchas', 'shower', 30),
  ('vestuarios', 'Vestuarios', 'shirt', 40),
  ('iluminacion', 'Iluminación', 'lightbulb', 50),
  ('graderias', 'Graderías', 'users', 60),
  ('parrillero', 'Parrillero', 'flame', 70),
  ('bebidas', 'Venta de bebidas', 'cup', 80),
  ('comida', 'Venta de comida', 'utensils', 90),
  ('alquiler-equipamiento', 'Alquiler de equipamiento', 'package', 100);

create table public.venue_services (
  venue_id uuid not null references public.venues (id) on delete cascade,
  service_id bigint not null references public.services (id) on delete restrict,
  primary key (venue_id, service_id)
);

create table public.venue_opening_hours (
  venue_id uuid not null references public.venues (id) on delete cascade,
  day_of_week smallint not null,
  opens_at time,
  closes_at time,
  is_closed boolean not null default false,
  primary key (venue_id, day_of_week),
  constraint venue_hours_day_range check (day_of_week between 0 and 6),
  constraint venue_hours_valid_times check (
    (is_closed and opens_at is null and closes_at is null)
    or (not is_closed and opens_at is not null and closes_at is not null and opens_at < closes_at)
  )
);

create table public.venue_photos (
  id uuid primary key default gen_random_uuid(),
  venue_id uuid not null references public.venues (id) on delete cascade,
  object_path text not null unique,
  kind public.venue_photo_kind not null,
  alt_text text not null,
  sort_order smallint not null default 0,
  created_by uuid not null references public.profiles (id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  constraint venue_photos_path_format check (object_path !~ '(^|/)\.\.?(/|$)'),
  constraint venue_photos_alt_length check (char_length(alt_text) between 3 and 160)
);

create unique index venue_photos_one_logo_idx on public.venue_photos (venue_id) where kind = 'logo';
create unique index venue_photos_one_cover_idx on public.venue_photos (venue_id) where kind = 'cover';
create index venue_photos_gallery_order_idx on public.venue_photos (venue_id, kind, sort_order, created_at);

create table public.venue_status_history (
  id bigint generated always as identity primary key,
  venue_id uuid not null references public.venues (id) on delete cascade,
  from_status public.venue_status,
  to_status public.venue_status not null,
  note text,
  changed_by uuid not null references public.profiles (id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  constraint venue_history_note_length check (note is null or char_length(note) between 5 and 1000)
);

create index venue_status_history_venue_idx on public.venue_status_history (venue_id, created_at desc);

alter table public.venues enable row level security;
alter table public.services enable row level security;
alter table public.venue_services enable row level security;
alter table public.venue_opening_hours enable row level security;
alter table public.venue_photos enable row level security;
alter table public.venue_status_history enable row level security;

revoke all on table public.venues, public.services, public.venue_services,
  public.venue_opening_hours, public.venue_photos, public.venue_status_history
  from anon, authenticated;

grant select on table public.venues, public.services, public.venue_services,
  public.venue_opening_hours, public.venue_photos to anon, authenticated;
grant select on table public.venue_status_history to authenticated;

create policy "venues_read_approved_or_authorized"
on public.venues for select
to anon, authenticated
using (
  status = 'approved'
  or owner_id = (select auth.uid())
  or (select private.current_user_role()) = 'super_admin'
);

create policy "services_read_active"
on public.services for select
to anon, authenticated
using (is_active or (select private.current_user_role()) = 'super_admin');

create policy "venue_services_read_approved_or_authorized"
on public.venue_services for select
to anon, authenticated
using (
  exists (
    select 1 from public.venues v
    where v.id = venue_id
      and (
        v.status = 'approved'
        or v.owner_id = (select auth.uid())
        or (select private.current_user_role()) = 'super_admin'
      )
  )
);

create policy "venue_hours_read_approved_or_authorized"
on public.venue_opening_hours for select
to anon, authenticated
using (
  exists (
    select 1 from public.venues v
    where v.id = venue_id
      and (
        v.status = 'approved'
        or v.owner_id = (select auth.uid())
        or (select private.current_user_role()) = 'super_admin'
      )
  )
);

create policy "venue_photos_read_approved_or_authorized"
on public.venue_photos for select
to anon, authenticated
using (
  exists (
    select 1 from public.venues v
    where v.id = venue_id
      and (
        v.status = 'approved'
        or v.owner_id = (select auth.uid())
        or (select private.current_user_role()) = 'super_admin'
      )
  )
);

create policy "venue_history_read_owner_or_admin"
on public.venue_status_history for select
to authenticated
using (
  exists (
    select 1 from public.venues v
    where v.id = venue_id
      and (
        v.owner_id = (select auth.uid())
        or (select private.current_user_role()) = 'super_admin'
      )
  )
);

create policy "profiles_admin_select"
on public.profiles for select
to authenticated
using ((select private.current_user_role()) = 'super_admin');

create function private.slugify(p_value text)
returns text
language sql
immutable
set search_path = ''
as $$
  select trim(both '-' from regexp_replace(
    lower(translate(trim(p_value), 'áéíóúÁÉÍÓÚñÑüÜ', 'aeiouAEIOUnNuU')),
    '[^a-z0-9]+', '-', 'g'
  ))
$$;

revoke execute on function private.slugify(text) from public, anon, authenticated;

create function public.save_my_venue(
  p_commercial_name text,
  p_description text,
  p_phone_e164 text,
  p_whatsapp_e164 text,
  p_address text,
  p_zone text,
  p_city text,
  p_latitude numeric,
  p_longitude numeric,
  p_service_slugs text[],
  p_hours jsonb
)
returns public.venues
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_venue public.venues;
  v_venue_id uuid;
  v_slug text;
  v_service_count integer;
  v_requested_service_count integer;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if (select private.current_user_role()) <> 'venue_owner' then
    raise exception 'Venue owner role required' using errcode = '42501';
  end if;

  if char_length(trim(coalesce(p_commercial_name, ''))) not between 3 and 120
     or char_length(trim(coalesce(p_description, ''))) not between 30 and 2000
     or char_length(trim(coalesce(p_address, ''))) not between 5 and 240
     or char_length(trim(coalesce(p_zone, ''))) not between 2 and 100
     or char_length(trim(coalesce(p_city, ''))) not between 2 and 100 then
    raise exception 'Invalid venue text fields' using errcode = '22023';
  end if;

  if p_phone_e164 is null or p_phone_e164 !~ '^\+[1-9][0-9]{7,14}$'
     or p_whatsapp_e164 is null or p_whatsapp_e164 !~ '^\+[1-9][0-9]{7,14}$' then
    raise exception 'Phones must use E.164 format' using errcode = '22023';
  end if;

  if p_latitude is null or p_latitude not between -90 and 90
     or p_longitude is null or p_longitude not between -180 and 180 then
    raise exception 'Invalid coordinates' using errcode = '22023';
  end if;

  if coalesce(array_length(p_service_slugs, 1), 0) < 1 then
    raise exception 'At least one service is required' using errcode = '22023';
  end if;

  if jsonb_typeof(p_hours) <> 'array' or jsonb_array_length(p_hours) <> 7 then
    raise exception 'Seven opening-hour entries are required' using errcode = '22023';
  end if;

  select * into v_venue
  from public.venues
  where owner_id = v_user_id
  for update;

  if found and v_venue.status not in ('draft', 'rejected', 'changes_requested') then
    raise exception 'Venue cannot be edited in its current status' using errcode = '42501';
  end if;

  if not found then
    v_venue_id := gen_random_uuid();
    v_slug := private.slugify(p_commercial_name) || '-' || left(v_venue_id::text, 8);

    insert into public.venues (
      id, owner_id, commercial_name, slug, description, phone_e164,
      whatsapp_e164, address, zone, city, latitude, longitude
    ) values (
      v_venue_id, v_user_id, trim(p_commercial_name), v_slug, trim(p_description),
      p_phone_e164, p_whatsapp_e164, trim(p_address), trim(p_zone), trim(p_city),
      p_latitude, p_longitude
    ) returning * into v_venue;

    insert into public.venue_status_history (venue_id, from_status, to_status, changed_by)
    values (v_venue.id, null, 'draft', v_user_id);
  else
    update public.venues
    set commercial_name = trim(p_commercial_name),
        description = trim(p_description),
        phone_e164 = p_phone_e164,
        whatsapp_e164 = p_whatsapp_e164,
        address = trim(p_address),
        zone = trim(p_zone),
        city = trim(p_city),
        latitude = p_latitude,
        longitude = p_longitude
    where id = v_venue.id
    returning * into v_venue;
  end if;

  select count(*), count(distinct requested_slug)
  into v_service_count, v_requested_service_count
  from unnest(p_service_slugs) requested_slug
  join public.services s on s.slug = requested_slug and s.is_active;

  if v_service_count <> coalesce(array_length(p_service_slugs, 1), 0)
     or v_requested_service_count <> v_service_count then
    raise exception 'Unknown or duplicate service' using errcode = '22023';
  end if;

  delete from public.venue_services where venue_id = v_venue.id;
  insert into public.venue_services (venue_id, service_id)
  select v_venue.id, s.id
  from public.services s
  where s.slug = any(p_service_slugs) and s.is_active;

  delete from public.venue_opening_hours where venue_id = v_venue.id;
  insert into public.venue_opening_hours (venue_id, day_of_week, opens_at, closes_at, is_closed)
  select
    v_venue.id,
    (item ->> 'day_of_week')::smallint,
    case when (item ->> 'is_closed')::boolean then null else (item ->> 'opens_at')::time end,
    case when (item ->> 'is_closed')::boolean then null else (item ->> 'closes_at')::time end,
    (item ->> 'is_closed')::boolean
  from jsonb_array_elements(p_hours) item;

  return v_venue;
exception
  when unique_violation or check_violation or invalid_text_representation then
    raise exception 'Invalid or duplicated venue data' using errcode = '22023';
end;
$$;

revoke execute on function public.save_my_venue(text, text, text, text, text, text, text, numeric, numeric, text[], jsonb)
  from public, anon;
grant execute on function public.save_my_venue(text, text, text, text, text, text, text, numeric, numeric, text[], jsonb)
  to authenticated;

create function public.register_my_venue_photo(
  p_object_path text,
  p_kind public.venue_photo_kind,
  p_alt_text text
)
returns public.venue_photos
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_venue public.venues;
  v_photo public.venue_photos;
begin
  select * into v_venue
  from public.venues
  where owner_id = v_user_id;

  if v_user_id is null or not found or v_venue.status not in ('draft', 'rejected', 'changes_requested') then
    raise exception 'Editable venue required' using errcode = '42501';
  end if;

  if p_object_path is null
     or split_part(p_object_path, '/', 1) <> v_venue.id::text
     or p_object_path ~ '(^|/)\.\.?(/|$)'
     or char_length(trim(coalesce(p_alt_text, ''))) not between 3 and 160 then
    raise exception 'Invalid photo data' using errcode = '22023';
  end if;

  if p_kind = 'gallery' and (
    select count(*) from public.venue_photos where venue_id = v_venue.id and kind = 'gallery'
  ) >= 10 then
    raise exception 'Gallery limit reached' using errcode = '22023';
  end if;

  insert into public.venue_photos (venue_id, object_path, kind, alt_text, created_by)
  values (v_venue.id, p_object_path, p_kind, trim(p_alt_text), v_user_id)
  returning * into v_photo;

  return v_photo;
end;
$$;

revoke execute on function public.register_my_venue_photo(text, public.venue_photo_kind, text) from public, anon;
grant execute on function public.register_my_venue_photo(text, public.venue_photo_kind, text) to authenticated;

create function public.delete_my_venue_photo(p_photo_id uuid)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_object_path text;
begin
  delete from public.venue_photos p
  using public.venues v
  where p.id = p_photo_id
    and p.venue_id = v.id
    and v.owner_id = v_user_id
    and v.status in ('draft', 'rejected', 'changes_requested')
  returning p.object_path into v_object_path;

  if v_object_path is null then
    raise exception 'Editable photo not found' using errcode = '42501';
  end if;

  return v_object_path;
end;
$$;

revoke execute on function public.delete_my_venue_photo(uuid) from public, anon;
grant execute on function public.delete_my_venue_photo(uuid) to authenticated;

create function public.submit_my_venue(p_venue_id uuid)
returns public.venues
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_venue public.venues;
  v_previous_status public.venue_status;
begin
  select * into v_venue
  from public.venues
  where id = p_venue_id and owner_id = v_user_id
  for update;

  if not found or v_venue.status not in ('draft', 'rejected', 'changes_requested') then
    raise exception 'Editable venue not found' using errcode = '42501';
  end if;

  if not exists (select 1 from public.venue_services where venue_id = v_venue.id)
     or not exists (select 1 from public.venue_opening_hours where venue_id = v_venue.id and not is_closed)
     or not exists (select 1 from public.venue_photos where venue_id = v_venue.id and kind = 'logo')
     or not exists (select 1 from public.venue_photos where venue_id = v_venue.id and kind = 'cover') then
    raise exception 'Venue needs services, opening hours, logo and cover' using errcode = '22023';
  end if;

  v_previous_status := v_venue.status;

  update public.venues
  set status = 'pending_approval',
      submitted_at = timezone('utc', now()),
      review_note = null,
      reviewed_at = null,
      reviewed_by = null
  where id = v_venue.id
  returning * into v_venue;

  insert into public.venue_status_history (venue_id, from_status, to_status, changed_by)
  values (v_venue.id, v_previous_status, 'pending_approval', v_user_id);

  return v_venue;
end;
$$;

revoke execute on function public.submit_my_venue(uuid) from public, anon;
grant execute on function public.submit_my_venue(uuid) to authenticated;

create function public.review_venue(
  p_venue_id uuid,
  p_decision text,
  p_note text default null
)
returns public.venues
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_venue public.venues;
  v_new_status public.venue_status;
  v_clean_note text := nullif(trim(coalesce(p_note, '')), '');
begin
  if v_user_id is null or (select private.current_user_role()) <> 'super_admin' then
    raise exception 'Super admin role required' using errcode = '42501';
  end if;

  select * into v_venue
  from public.venues
  where id = p_venue_id
  for update;

  if not found or v_venue.status <> 'pending_approval' then
    raise exception 'Pending venue not found' using errcode = '22023';
  end if;

  v_new_status := case p_decision
    when 'approve' then 'approved'::public.venue_status
    when 'reject' then 'rejected'::public.venue_status
    when 'request_changes' then 'changes_requested'::public.venue_status
    else null
  end;

  if v_new_status is null then
    raise exception 'Invalid review decision' using errcode = '22023';
  end if;

  if v_new_status <> 'approved' and char_length(coalesce(v_clean_note, '')) not between 5 and 1000 then
    raise exception 'A review note is required' using errcode = '22023';
  end if;

  update public.venues
  set status = v_new_status,
      review_note = v_clean_note,
      reviewed_at = timezone('utc', now()),
      reviewed_by = v_user_id,
      approved_at = case when v_new_status = 'approved' then timezone('utc', now()) else approved_at end
  where id = v_venue.id
  returning * into v_venue;

  insert into public.venue_status_history (venue_id, from_status, to_status, note, changed_by)
  values (v_venue.id, 'pending_approval', v_new_status, v_clean_note, v_user_id);

  return v_venue;
end;
$$;

revoke execute on function public.review_venue(uuid, text, text) from public, anon;
grant execute on function public.review_venue(uuid, text, text) to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'venue-media',
  'venue-media',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create policy "venue_media_read_approved_or_authorized"
on storage.objects for select
to anon, authenticated
using (
  bucket_id = 'venue-media'
  and exists (
    select 1 from public.venues v
    where v.id::text = (storage.foldername(name))[1]
      and (
        v.status = 'approved'
        or v.owner_id = (select auth.uid())
        or (select private.current_user_role()) = 'super_admin'
      )
  )
);

create policy "venue_media_owner_upload"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'venue-media'
  and exists (
    select 1 from public.venues v
    where v.id::text = (storage.foldername(name))[1]
      and v.owner_id = (select auth.uid())
      and v.status in ('draft', 'rejected', 'changes_requested')
  )
);

create policy "venue_media_owner_update"
on storage.objects for update
to authenticated
using (
  bucket_id = 'venue-media'
  and exists (
    select 1 from public.venues v
    where v.id::text = (storage.foldername(name))[1]
      and v.owner_id = (select auth.uid())
      and v.status in ('draft', 'rejected', 'changes_requested')
  )
)
with check (
  bucket_id = 'venue-media'
  and exists (
    select 1 from public.venues v
    where v.id::text = (storage.foldername(name))[1]
      and v.owner_id = (select auth.uid())
      and v.status in ('draft', 'rejected', 'changes_requested')
  )
);

create policy "venue_media_owner_delete"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'venue-media'
  and exists (
    select 1 from public.venues v
    where v.id::text = (storage.foldername(name))[1]
      and v.owner_id = (select auth.uid())
      and v.status in ('draft', 'rejected', 'changes_requested')
  )
);

commit;
