begin;

create type public.court_status as enum ('draft', 'active', 'inactive');
create type public.court_photo_kind as enum ('cover', 'gallery');

create table public.sports (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  sort_order smallint not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  constraint sports_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint sports_name_length check (char_length(name) between 2 and 80)
);

create table public.sport_modalities (
  id bigint generated by default as identity primary key,
  sport_id bigint not null references public.sports (id) on delete restrict,
  slug text not null,
  name text not null,
  default_capacity smallint not null,
  sort_order smallint not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  unique (sport_id, slug),
  unique (id, sport_id),
  constraint sport_modalities_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint sport_modalities_name_length check (char_length(name) between 2 and 80),
  constraint sport_modalities_capacity_range check (default_capacity between 1 and 100)
);

create table public.court_surfaces (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  sort_order smallint not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  constraint court_surfaces_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint court_surfaces_name_length check (char_length(name) between 2 and 80)
);

create table public.court_features (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  icon text not null,
  sort_order smallint not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  constraint court_features_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint court_features_name_length check (char_length(name) between 2 and 80),
  constraint court_features_icon_length check (char_length(icon) between 2 and 40)
);

insert into public.sports (slug, name, sort_order) values
  ('futbol', 'Fútbol', 10),
  ('padel', 'Pádel', 20),
  ('wally', 'Wally', 30);

insert into public.sport_modalities (sport_id, slug, name, default_capacity, sort_order)
select s.id, seed.slug, seed.name, seed.default_capacity, seed.sort_order
from public.sports s
join (values
  ('futbol', 'futbol-5', 'Fútbol 5', 10, 10),
  ('futbol', 'futbol-7', 'Fútbol 7', 14, 20),
  ('futbol', 'futbol-8', 'Fútbol 8', 16, 30),
  ('futbol', 'futbol-11', 'Fútbol 11', 22, 40),
  ('padel', 'padel-individual', 'Pádel individual', 2, 10),
  ('padel', 'padel-dobles', 'Pádel dobles', 4, 20),
  ('wally', 'wally-3x3', 'Wally 3 vs 3', 6, 10),
  ('wally', 'wally-4x4', 'Wally 4 vs 4', 8, 20)
) as seed(sport_slug, slug, name, default_capacity, sort_order)
  on seed.sport_slug = s.slug;

insert into public.court_surfaces (slug, name, sort_order) values
  ('cesped-sintetico', 'Césped sintético', 10),
  ('cesped-natural', 'Césped natural', 20),
  ('piso-sintetico', 'Piso sintético', 30),
  ('cemento', 'Cemento', 40),
  ('parquet', 'Parquet', 50),
  ('arcilla', 'Arcilla', 60);

insert into public.court_features (slug, name, icon, sort_order) values
  ('graderias', 'Graderías', 'users', 10),
  ('marcador', 'Marcador', 'scoreboard', 20),
  ('red-proteccion', 'Red de protección', 'shield', 30),
  ('equipamiento-incluido', 'Equipamiento incluido', 'package', 40),
  ('climatizacion', 'Climatización', 'snowflake', 50);

create table public.courts (
  id uuid primary key default gen_random_uuid(),
  venue_id uuid not null references public.venues (id) on delete cascade,
  sport_id bigint not null references public.sports (id) on delete restrict,
  modality_id bigint not null,
  surface_id bigint not null references public.court_surfaces (id) on delete restrict,
  name text not null,
  slug text not null,
  capacity smallint not null,
  length_m numeric(6, 2) not null,
  width_m numeric(6, 2) not null,
  is_roofed boolean not null default false,
  has_lighting boolean not null default false,
  status public.court_status not null default 'draft',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (venue_id, slug),
  constraint courts_modality_matches_sport foreign key (modality_id, sport_id)
    references public.sport_modalities (id, sport_id) on delete restrict,
  constraint courts_name_length check (char_length(name) between 3 and 100),
  constraint courts_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint courts_capacity_range check (capacity between 1 and 100),
  constraint courts_length_range check (length_m between 3 and 200),
  constraint courts_width_range check (width_m between 2 and 150)
);

comment on table public.courts is 'Canchas administradas por un complejo aprobado. Los precios y horarios se agregan en la fase 5.';
comment on column public.courts.status is 'draft e inactive son privados; active se muestra públicamente si el complejo sigue aprobado.';

create index courts_venue_status_idx on public.courts (venue_id, status);
create index courts_sport_idx on public.courts (sport_id);
create index courts_modality_sport_idx on public.courts (modality_id, sport_id);
create index courts_surface_idx on public.courts (surface_id);

create trigger courts_set_updated_at
before update on public.courts
for each row execute function private.set_updated_at();

create table public.court_durations (
  court_id uuid not null references public.courts (id) on delete cascade,
  duration_minutes smallint not null,
  primary key (court_id, duration_minutes),
  constraint court_durations_supported check (duration_minutes in (30, 60))
);

create table public.court_feature_assignments (
  court_id uuid not null references public.courts (id) on delete cascade,
  feature_id bigint not null references public.court_features (id) on delete restrict,
  primary key (court_id, feature_id)
);

create index court_feature_assignments_feature_idx on public.court_feature_assignments (feature_id);

create table public.court_photos (
  id uuid primary key default gen_random_uuid(),
  court_id uuid not null references public.courts (id) on delete cascade,
  object_path text not null unique,
  kind public.court_photo_kind not null,
  alt_text text not null,
  sort_order smallint not null default 0,
  created_by uuid not null references public.profiles (id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  constraint court_photos_path_format check (object_path !~ '(^|/)\.\.?(/|$)'),
  constraint court_photos_alt_length check (char_length(alt_text) between 3 and 160)
);

create unique index court_photos_one_cover_idx on public.court_photos (court_id) where kind = 'cover';
create index court_photos_order_idx on public.court_photos (court_id, kind, sort_order, created_at);
create index court_photos_created_by_idx on public.court_photos (created_by);

alter table public.sports enable row level security;
alter table public.sport_modalities enable row level security;
alter table public.court_surfaces enable row level security;
alter table public.court_features enable row level security;
alter table public.courts enable row level security;
alter table public.court_durations enable row level security;
alter table public.court_feature_assignments enable row level security;
alter table public.court_photos enable row level security;

revoke all on table public.sports, public.sport_modalities, public.court_surfaces,
  public.court_features, public.courts, public.court_durations,
  public.court_feature_assignments, public.court_photos from anon, authenticated;

grant select on table public.sports, public.sport_modalities, public.court_surfaces,
  public.court_features, public.courts, public.court_durations,
  public.court_feature_assignments, public.court_photos to anon, authenticated;

create policy "sports_anon_read_active"
on public.sports for select to anon
using (is_active);

create policy "sports_authenticated_read_visible"
on public.sports for select to authenticated
using (is_active or (select private.current_user_role()) = 'super_admin');

create policy "sport_modalities_anon_read_active"
on public.sport_modalities for select to anon
using (is_active and exists (select 1 from public.sports s where s.id = sport_id and s.is_active));

create policy "sport_modalities_authenticated_read_visible"
on public.sport_modalities for select to authenticated
using (
  (is_active and exists (select 1 from public.sports s where s.id = sport_id and s.is_active))
  or (select private.current_user_role()) = 'super_admin'
);

create policy "court_surfaces_anon_read_active"
on public.court_surfaces for select to anon
using (is_active);

create policy "court_surfaces_authenticated_read_visible"
on public.court_surfaces for select to authenticated
using (is_active or (select private.current_user_role()) = 'super_admin');

create policy "court_features_anon_read_active"
on public.court_features for select to anon
using (is_active);

create policy "court_features_authenticated_read_visible"
on public.court_features for select to authenticated
using (is_active or (select private.current_user_role()) = 'super_admin');

create policy "courts_anon_read_active"
on public.courts for select to anon
using (
  status = 'active'
  and exists (select 1 from public.venues v where v.id = venue_id and v.status = 'approved')
);

create policy "courts_authenticated_read_visible"
on public.courts for select to authenticated
using (
  (
    status = 'active'
    and exists (select 1 from public.venues v where v.id = venue_id and v.status = 'approved')
  )
  or exists (select 1 from public.venues v where v.id = venue_id and v.owner_id = (select auth.uid()))
  or (select private.current_user_role()) = 'super_admin'
);

create policy "court_durations_anon_read_active"
on public.court_durations for select to anon
using (
  exists (
    select 1 from public.courts c
    join public.venues v on v.id = c.venue_id
    where c.id = court_id and c.status = 'active' and v.status = 'approved'
  )
);

create policy "court_durations_authenticated_read_visible"
on public.court_durations for select to authenticated
using (
  exists (
    select 1 from public.courts c
    join public.venues v on v.id = c.venue_id
    where c.id = court_id
      and ((c.status = 'active' and v.status = 'approved') or v.owner_id = (select auth.uid()))
  )
  or (select private.current_user_role()) = 'super_admin'
);

create policy "court_feature_assignments_anon_read_active"
on public.court_feature_assignments for select to anon
using (
  exists (
    select 1 from public.courts c
    join public.venues v on v.id = c.venue_id
    where c.id = court_id and c.status = 'active' and v.status = 'approved'
  )
);

create policy "court_feature_assignments_authenticated_read_visible"
on public.court_feature_assignments for select to authenticated
using (
  exists (
    select 1 from public.courts c
    join public.venues v on v.id = c.venue_id
    where c.id = court_id
      and ((c.status = 'active' and v.status = 'approved') or v.owner_id = (select auth.uid()))
  )
  or (select private.current_user_role()) = 'super_admin'
);

create policy "court_photos_anon_read_active"
on public.court_photos for select to anon
using (
  exists (
    select 1 from public.courts c
    join public.venues v on v.id = c.venue_id
    where c.id = court_id and c.status = 'active' and v.status = 'approved'
  )
);

create policy "court_photos_authenticated_read_visible"
on public.court_photos for select to authenticated
using (
  exists (
    select 1 from public.courts c
    join public.venues v on v.id = c.venue_id
    where c.id = court_id
      and ((c.status = 'active' and v.status = 'approved') or v.owner_id = (select auth.uid()))
  )
  or (select private.current_user_role()) = 'super_admin'
);

create function public.save_my_court(
  p_court_id uuid,
  p_name text,
  p_sport_slug text,
  p_modality_slug text,
  p_surface_slug text,
  p_capacity smallint,
  p_length_m numeric,
  p_width_m numeric,
  p_is_roofed boolean,
  p_has_lighting boolean,
  p_duration_minutes smallint[],
  p_feature_slugs text[]
)
returns public.courts
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_venue public.venues;
  v_court public.courts;
  v_court_id uuid;
  v_sport_id bigint;
  v_modality_id bigint;
  v_surface_id bigint;
  v_feature_count integer;
  v_requested_feature_count integer;
begin
  if v_user_id is null or (select private.current_user_role()) <> 'venue_owner' then
    raise exception 'Venue owner role required' using errcode = '42501';
  end if;

  select * into v_venue
  from public.venues
  where owner_id = v_user_id and status = 'approved';

  if not found then
    raise exception 'An approved venue is required' using errcode = '42501';
  end if;

  if char_length(trim(coalesce(p_name, ''))) not between 3 and 100
     or p_capacity is null or p_capacity not between 1 and 100
     or p_length_m is null or p_length_m not between 3 and 200
     or p_width_m is null or p_width_m not between 2 and 150 then
    raise exception 'Invalid court data' using errcode = '22023';
  end if;

  if coalesce(array_length(p_duration_minutes, 1), 0) < 1
     or exists (select 1 from unnest(p_duration_minutes) value where value not in (30, 60))
     or (select count(*) from unnest(p_duration_minutes)) <> (select count(distinct value) from unnest(p_duration_minutes) value) then
    raise exception 'Invalid or duplicate durations' using errcode = '22023';
  end if;

  select id into v_sport_id from public.sports where slug = p_sport_slug and is_active;
  select id into v_modality_id from public.sport_modalities where slug = p_modality_slug and sport_id = v_sport_id and is_active;
  select id into v_surface_id from public.court_surfaces where slug = p_surface_slug and is_active;

  if v_sport_id is null or v_modality_id is null or v_surface_id is null then
    raise exception 'Unknown sport, modality or surface' using errcode = '22023';
  end if;

  select count(*), count(distinct requested_slug)
  into v_feature_count, v_requested_feature_count
  from unnest(coalesce(p_feature_slugs, array[]::text[])) requested_slug
  join public.court_features f on f.slug = requested_slug and f.is_active;

  if v_feature_count <> coalesce(array_length(p_feature_slugs, 1), 0)
     or v_requested_feature_count <> v_feature_count then
    raise exception 'Unknown or duplicate feature' using errcode = '22023';
  end if;

  if p_court_id is null then
    v_court_id := gen_random_uuid();
    insert into public.courts (
      id, venue_id, sport_id, modality_id, surface_id, name, slug, capacity,
      length_m, width_m, is_roofed, has_lighting
    ) values (
      v_court_id, v_venue.id, v_sport_id, v_modality_id, v_surface_id,
      trim(p_name), private.slugify(p_name) || '-' || left(v_court_id::text, 8), p_capacity,
      p_length_m, p_width_m, coalesce(p_is_roofed, false), coalesce(p_has_lighting, false)
    ) returning * into v_court;
  else
    update public.courts
    set sport_id = v_sport_id,
        modality_id = v_modality_id,
        surface_id = v_surface_id,
        name = trim(p_name),
        capacity = p_capacity,
        length_m = p_length_m,
        width_m = p_width_m,
        is_roofed = coalesce(p_is_roofed, false),
        has_lighting = coalesce(p_has_lighting, false)
    where id = p_court_id and venue_id = v_venue.id
    returning * into v_court;

    if not found then
      raise exception 'Court not found' using errcode = '22023';
    end if;
  end if;

  delete from public.court_durations where court_id = v_court.id;
  insert into public.court_durations (court_id, duration_minutes)
  select v_court.id, value from unnest(p_duration_minutes) value;

  delete from public.court_feature_assignments where court_id = v_court.id;
  insert into public.court_feature_assignments (court_id, feature_id)
  select v_court.id, f.id
  from public.court_features f
  where f.slug = any(coalesce(p_feature_slugs, array[]::text[])) and f.is_active;

  return v_court;
exception
  when unique_violation or check_violation or invalid_text_representation then
    raise exception 'Invalid or duplicated court data' using errcode = '22023';
end;
$$;

revoke execute on function public.save_my_court(uuid, text, text, text, text, smallint, numeric, numeric, boolean, boolean, smallint[], text[])
  from public, anon;
grant execute on function public.save_my_court(uuid, text, text, text, text, smallint, numeric, numeric, boolean, boolean, smallint[], text[])
  to authenticated;

create function public.set_my_court_status(p_court_id uuid, p_status text)
returns public.courts
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_court public.courts;
  v_target public.court_status;
begin
  if v_user_id is null or (select private.current_user_role()) <> 'venue_owner' then
    raise exception 'Venue owner role required' using errcode = '42501';
  end if;

  v_target := case p_status
    when 'active' then 'active'::public.court_status
    when 'inactive' then 'inactive'::public.court_status
    else null
  end;

  if v_target is null then
    raise exception 'Invalid court status' using errcode = '22023';
  end if;

  select c.* into v_court
  from public.courts c
  join public.venues v on v.id = c.venue_id
  where c.id = p_court_id and v.owner_id = v_user_id and v.status = 'approved'
  for update of c;

  if not found then
    raise exception 'Court not found' using errcode = '22023';
  end if;

  if v_target = 'active' and (
    not exists (select 1 from public.court_durations d where d.court_id = v_court.id)
    or not exists (select 1 from public.court_photos p where p.court_id = v_court.id and p.kind = 'cover')
  ) then
    raise exception 'A duration and cover photo are required' using errcode = '22023';
  end if;

  update public.courts set status = v_target where id = v_court.id returning * into v_court;
  return v_court;
end;
$$;

revoke execute on function public.set_my_court_status(uuid, text) from public, anon;
grant execute on function public.set_my_court_status(uuid, text) to authenticated;

create function public.register_my_court_photo(
  p_court_id uuid,
  p_object_path text,
  p_kind public.court_photo_kind,
  p_alt_text text
)
returns public.court_photos
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_court public.courts;
  v_venue_id uuid;
  v_photo public.court_photos;
begin
  if v_user_id is null or (select private.current_user_role()) <> 'venue_owner' then
    raise exception 'Venue owner role required' using errcode = '42501';
  end if;

  select c.* into v_court
  from public.courts c
  join public.venues v on v.id = c.venue_id
  where c.id = p_court_id and v.owner_id = v_user_id and v.status = 'approved';

  if not found then
    raise exception 'Court not found' using errcode = '22023';
  end if;

  v_venue_id := v_court.venue_id;

  if p_object_path !~ ('^' || v_venue_id::text || '/courts/' || v_court.id::text || '/(cover|gallery)/[A-Za-z0-9._-]+$')
     or char_length(trim(coalesce(p_alt_text, ''))) not between 3 and 160 then
    raise exception 'Invalid court photo' using errcode = '22023';
  end if;

  if p_kind = 'gallery' and (select count(*) from public.court_photos where court_id = v_court.id and kind = 'gallery') >= 8 then
    raise exception 'Court gallery limit reached' using errcode = '22023';
  end if;

  insert into public.court_photos (court_id, object_path, kind, alt_text, created_by)
  values (v_court.id, p_object_path, p_kind, trim(p_alt_text), v_user_id)
  returning * into v_photo;

  return v_photo;
exception
  when unique_violation or check_violation then
    raise exception 'Invalid or duplicated court photo' using errcode = '22023';
end;
$$;

revoke execute on function public.register_my_court_photo(uuid, text, public.court_photo_kind, text) from public, anon;
grant execute on function public.register_my_court_photo(uuid, text, public.court_photo_kind, text) to authenticated;

create function public.delete_my_court_photo(p_photo_id uuid)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_object_path text;
begin
  if v_user_id is null or (select private.current_user_role()) <> 'venue_owner' then
    raise exception 'Venue owner role required' using errcode = '42501';
  end if;

  delete from public.court_photos p
  using public.courts c, public.venues v
  where p.id = p_photo_id
    and c.id = p.court_id
    and v.id = c.venue_id
    and v.owner_id = v_user_id
    and v.status = 'approved'
  returning p.object_path into v_object_path;

  if v_object_path is null then
    raise exception 'Court photo not found' using errcode = '22023';
  end if;

  return v_object_path;
end;
$$;

revoke execute on function public.delete_my_court_photo(uuid) from public, anon;
grant execute on function public.delete_my_court_photo(uuid) to authenticated;

drop policy "venue_media_anon_read_approved" on storage.objects;
drop policy "venue_media_authenticated_read_visible" on storage.objects;
drop policy "venue_media_owner_upload" on storage.objects;
drop policy "venue_media_owner_update" on storage.objects;
drop policy "venue_media_owner_delete" on storage.objects;

create policy "venue_media_anon_read_visible"
on storage.objects for select to anon
using (
  bucket_id = 'venue-media'
  and exists (
    select 1 from public.venues v
    where v.id::text = (storage.foldername(name))[1]
      and v.status = 'approved'
      and (
        (storage.foldername(name))[2] in ('logo', 'cover', 'gallery')
        or (
          (storage.foldername(name))[2] = 'courts'
          and exists (
            select 1 from public.courts c
            where c.id::text = (storage.foldername(name))[3]
              and c.venue_id = v.id and c.status = 'active'
          )
        )
      )
  )
);

create policy "venue_media_authenticated_read_visible"
on storage.objects for select to authenticated
using (
  bucket_id = 'venue-media'
  and exists (
    select 1 from public.venues v
    where v.id::text = (storage.foldername(name))[1]
      and (
        v.owner_id = (select auth.uid())
        or (select private.current_user_role()) = 'super_admin'
        or (
          v.status = 'approved'
          and (
            (storage.foldername(name))[2] in ('logo', 'cover', 'gallery')
            or (
              (storage.foldername(name))[2] = 'courts'
              and exists (
                select 1 from public.courts c
                where c.id::text = (storage.foldername(name))[3]
                  and c.venue_id = v.id and c.status = 'active'
              )
            )
          )
        )
      )
  )
);

create policy "venue_media_owner_upload"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'venue-media'
  and exists (
    select 1 from public.venues v
    where v.id::text = (storage.foldername(name))[1]
      and v.owner_id = (select auth.uid())
      and (
        (
          v.status in ('draft', 'rejected', 'changes_requested')
          and (storage.foldername(name))[2] in ('logo', 'cover', 'gallery')
        )
        or (
          v.status = 'approved'
          and (storage.foldername(name))[2] = 'courts'
          and (storage.foldername(name))[4] in ('cover', 'gallery')
          and exists (
            select 1 from public.courts c
            where c.id::text = (storage.foldername(name))[3] and c.venue_id = v.id
          )
        )
      )
  )
);

create policy "venue_media_owner_update"
on storage.objects for update to authenticated
using (
  bucket_id = 'venue-media'
  and exists (
    select 1 from public.venues v
    where v.id::text = (storage.foldername(name))[1]
      and v.owner_id = (select auth.uid())
      and (
        (v.status in ('draft', 'rejected', 'changes_requested') and (storage.foldername(name))[2] in ('logo', 'cover', 'gallery'))
        or (v.status = 'approved' and (storage.foldername(name))[2] = 'courts'
          and exists (select 1 from public.courts c where c.id::text = (storage.foldername(name))[3] and c.venue_id = v.id))
      )
  )
)
with check (
  bucket_id = 'venue-media'
  and exists (
    select 1 from public.venues v
    where v.id::text = (storage.foldername(name))[1]
      and v.owner_id = (select auth.uid())
      and (
        (v.status in ('draft', 'rejected', 'changes_requested') and (storage.foldername(name))[2] in ('logo', 'cover', 'gallery'))
        or (v.status = 'approved' and (storage.foldername(name))[2] = 'courts'
          and exists (select 1 from public.courts c where c.id::text = (storage.foldername(name))[3] and c.venue_id = v.id))
      )
  )
);

create policy "venue_media_owner_delete"
on storage.objects for delete to authenticated
using (
  bucket_id = 'venue-media'
  and exists (
    select 1 from public.venues v
    where v.id::text = (storage.foldername(name))[1]
      and v.owner_id = (select auth.uid())
      and (
        (v.status in ('draft', 'rejected', 'changes_requested') and (storage.foldername(name))[2] in ('logo', 'cover', 'gallery'))
        or (v.status = 'approved' and (storage.foldername(name))[2] = 'courts'
          and exists (select 1 from public.courts c where c.id::text = (storage.foldername(name))[3] and c.venue_id = v.id))
      )
  )
);

commit;
